import '../../api/users/methods.js';
import '../../api/vehicle-types/server/publications.js';
import '../../api/models/server/publications.js';
import '../../api/vehicles/methods.js';
import '../../api/vehicles/server/publications.js';
import '../../api/reservations/methods.js';
import '../../api/reservations/server/publications.js';
import '../../api/contacts/methods.js';
import '../../api/contacts/server/publications.js';
